name: Editor Publish
on: [workflow_dispatch]
jobs:
  checkVersion:
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check package version
        id: check
        uses: PostHog/check-package-version@v2
        with:
          path: ./apps/editor/
      - name: Cancel when unchanged
        uses: andymckay/cancel-action@0.2
        if: steps.check.outputs.is-new-version == 'false'
  # setup:
  #   needs: [checkVersion]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v2
  #     - name: Use Node.js 15.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '15.x'
  #     - name: Log
  #       run: 'echo "do it?"'
  #     - name: install
  #       run: |
  #         npm i -g @toast-ui/doc
  #         npm i -g lerna
  #         npm ci
  #     - name: build
  #       run: |
  #         npm run build toastmark
  #         npm run build editor
  #     - name: Use Node.js 10.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '10.x'
  #     - name: doc
  #       run: |
  #         npm run doc
  #         mv apps/editor/3.0.2 3.0.2
  #         mv -i apps/editor/_latest latest
  #         git stash --include-untracked
  #     - name: checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: gh-pages
  #     - name: Commit files
  #       run: |
  #         git config --local user.email 'js87zz.lee@nhn.com'
  #         git config --local user.name 'js87zz'
  #         git stash pop
  #         git add .
  #         git commit -m 'test'
  #     - name: Push changes
  #       uses: ad-m/github-push-action@master
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         branch: gh-pages



  # pre-check:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: eslint
  #       run: |
  #         npm run lint:all
  #     - name: check types
  #       run: |
  #         npm run test:types:all 
  # test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: toastmark unit, integration test
  #       run: |
  #         npm run test:ci toastmark
  #     - name: editor unit, integration test
  #       run: |
  #         npm run test:ci editor
  # plugin-test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: chart plugin unit, integration test
  #       run: |
  #         npm run test:ci chart
  #     - name: color syntax plugin unit, integration test
  #       run: |
  #         npm run test:ci color
  #     - name: code syntax highlighting plugin unit, integration test
  #       run: |
  #         npm run test:ci code
  #     - name: table merged cell plugin unit, integration test
  #       run: |
  #         npm run test:ci table
  #     - name: uml plugin unit, integration test
  #       run: |
  #         npm run test:ci uml
  
  doc:
    runs-on: ubuntu-latest
    needs: [checkVersion]
    steps:
      - uses: actions/checkout@v2
      - name: Check the package version
        id: check
        uses: PostHog/check-package-version@v2
        with:
          path: ./apps/editor/
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install
        run: |
          npm i -g @toast-ui/doc
          npm ci
      - name: Build
        run: |
          npm run build toastmark
          npm run build editor
      - name: doc
        run: |
          npm run doc
          mv apps/editor/${{ steps.check.outputs.committed-version }} ${{ steps.check.outputs.committed-version }}
          mv apps/editor/_latest latest
          git stash --include-untracked
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Commit files
        run: |
          git config --local user.email 'js87zz.lee@nhn.com'
          git config --local user.name 'js87zz'
          git stash pop
          git add .
          git commit -m '${{ steps.check.outputs.committed-version }}'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

          
