name: Editor Publish
on:
  push:
    tags:
      - '*'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm ci
        run: |
          npm ci
      - name: build toastmark
        run: |
          npm run build toastmark
      - name: build editor
        run: |
          npm run build editor
  # pre-check:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: eslint
  #       run: |
  #         npm run lint:all
  #     - name: check types
  #       run: |
  #         npm run test:types:all 
  # test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: toastmark unit, integration test
  #       run: |
  #         npm run test:ci toastmark
  #     - name: editor unit, integration test
  #       run: |
  #         npm run test:ci editor
  # plugin-test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: chart plugin unit, integration test
  #       run: |
  #         npm run test:ci chart
  #     - name: color syntax plugin unit, integration test
  #       run: |
  #         npm run test:ci color
  #     - name: code syntax highlighting plugin unit, integration test
  #       run: |
  #         npm run test:ci code
  #     - name: table merged cell plugin unit, integration test
  #       run: |
  #         npm run test:ci table
  #     - name: uml plugin unit, integration test
  #       run: |
  #         npm run test:ci uml
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install tuidoc
        run: |
          npm i -g @toast-ui/doc
      - name: doc
        run: |
          npm run doc