name: Editor Publish
on: [workflow_dispatch]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      # - name: npm ci
      #   run: |
      #     npm ci
      # - name: build toastmark
      #   run: |
      #     npm run build toastmark
      # - name: build editor
      #   run: |
      #     npm run build editor
      # - name: Use Node.js 10.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '10.x'
      # - name: install tuidoc
      #   run: |
      #     npm i -g @toast-ui/doc
      # - name: install lerna
      #   run: |
      #     npm i -g lerna
      # - name: doc
      #   run: |
      #     npm run doc
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      # - name: mv
      #   run: |
      #     mv apps/editor/_latest 3.0.2
      # - name: mv2
      #   run: |
      #     mv -i apps/editor/_latest latest
      # - name: push-origin
      #   run: |
      #     git add .
      #     git commit -m "test"
      #     git push origin gh-pages
  # pre-check:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: eslint
  #       run: |
  #         npm run lint:all
  #     - name: check types
  #       run: |
  #         npm run test:types:all 
  # test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: toastmark unit, integration test
  #       run: |
  #         npm run test:ci toastmark
  #     - name: editor unit, integration test
  #       run: |
  #         npm run test:ci editor
  # plugin-test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: chart plugin unit, integration test
  #       run: |
  #         npm run test:ci chart
  #     - name: color syntax plugin unit, integration test
  #       run: |
  #         npm run test:ci color
  #     - name: code syntax highlighting plugin unit, integration test
  #       run: |
  #         npm run test:ci code
  #     - name: table merged cell plugin unit, integration test
  #       run: |
  #         npm run test:ci table
  #     - name: uml plugin unit, integration test
  #       run: |
  #         npm run test:ci uml
  # doc:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v2
  #     - name: Use Node.js 10.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '10.x'
  #     - name: install tuidoc
  #       run: |
  #         npm i -g @toast-ui/doc
  #     - name: install lerna
  #       run: |
  #         npm i -g lerna
  #     - name: doc
  #       run: |
  #         npm run doc
  #     - name: checkout
  #       run: |
  #         git checkout gh-pages
  #     - name: mv
  #       run: |
  #         mv apps/editor/_latest 3.0.2
  #     - name: mv2
  #       run: |
  #         mv -i apps/editor/_latest latest
  #     - name: push-origin
  #       run: |
  #         git add .
  #         git commit -m "test"
  #         git push origin gh-pages

          
